[versions]
agp = "8.2.2"
revanced-patcher = "21.0.0"
# Tracking https://github.com/google/smali/issues/64.
#noinspection GradleDependency
smali = "3.0.5"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
